project/urls.py
from django.contrib import admin
from django.urls import path,include
from web import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urls)),
]

web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.urls import include
from web.views import account
from web.views import home
from web.views import project
from web.views import manage
from web.views import wiki
from web.views import file
from web.views import setting
from web.views import issues
from web.views import dashboard
from web.views import statistics

name = 'web'

urlpatterns = [
    re_path(r'^register/$', account.register, name='register'),
    re_path(r'^send_sms/$', account.send_sms, name='send_sms'),
    re_path(r'^login_sms/$', account.login_sms, name='login_sms'),
    re_path(r'^login/$', account.login, name='login'),
    re_path(r'^image/code/$', account.image_code, name='image_code'),
    re_path(r'^logout/$', account.logout, name='logout'),

    # 支付
    re_path(r'^price/$', home.price, name='price'),
    re_path(r'^payment/(?P<price_id>\d+)/$', home.payment, name='payment'),
    re_path(r'^pay_notify/$', home.pay_notify, name='pay_notify'),

    # 首页
    re_path(r'^index/$', home.index, name='index'),

    # 项目列表
    re_path(r'^project/', include([
        re_path(r'^list/$', project.project_list, name='project_list'),
        re_path(r'^star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
        re_path(r'^unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),
    ], None), None),

    # 项目管理
    re_path(r'^manage/(?P<project_id>\d+)/', include([
        re_path(r'^dashboard/$', dashboard.dashboard, name='dashboard'),

        re_path(r'^wiki/$', wiki.wiki, name='wiki'),
        re_path(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        re_path(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        re_path(r'^wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
        # wiki目录
        re_path(r'^wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),
        re_path(r'^wiki/uploads/$', wiki.wiki_uploads, name='wiki_uploads'),

        re_path(r'^file/$', file.file, name='file'),
        re_path(r'^file/delete/$', file.file_delete, name='file_delete'),
        re_path(r'^file/cos_credential/$', file.cos_credential, name='cos_credential'),
        re_path(r'^file/post/$', file.file_post, name='file_post'),
        re_path(r'^file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

        re_path(r'^setting/$', setting.setting, name='setting'),
        re_path(r'^setting/delete/$', setting.delete, name='setting_delete'),

        re_path(r'^issues/$', issues.issues, name='issues'),
        re_path(r'^issues/detail/(?P<issues_id>\d+)/$', issues.issues_detail, name='issues_detail'),
        re_path(r'^issues/record/(?P<issues_id>\d+)/$', issues.issues_record, name='issues_record'),
        re_path(r'^issues/change/(?P<issues_id>\d+)/$', issues.issues_change, name='issues_change'),
        re_path(r'^issues/invite/url/$', issues.issues_invite, name='issues_invite'),
        re_path(r'^issues_chart/$', dashboard.issues_chart, name='issues_chart'),
        re_path(r'^statistics/$', statistics.statistics, name='statistics'),
        re_path(r'^statistics_priority/$', statistics.statistics_priority, name='statistics_priority'),
        re_path(r'^statistics_project_user/$', statistics.statistics_project_user, name='statistics_project_user'),

    ], None), None),
    re_path(r'^invite_join/(?P<code>\w+)/$', issues.invite_join, name='invite_join'),
]

web/models.py
from django.db import models


# Create your models here.

class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=32, db_index=True)  # 开启索引
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile_phone = models.CharField(verbose_name='手机号', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)

    def __str__(self):
        return self.username


class TtemPrice(models.Model):
    type = models.CharField(verbose_name='类型', max_length=32)
    title = models.CharField(verbose_name='标题', max_length=64)
    price = models.IntegerField(verbose_name='价格/年')


class PricePolicy(models.Model):
    """ 价格策略 """
    category_choices = (
        (2, '收费版'),
        (3, '其他'),
    )
    category = models.SmallIntegerField(verbose_name='收费类型', default=2, choices=category_choices)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')  # 正整数类型

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间', help_text='G')
    per_file_size = models.PositiveIntegerField(verbose_name='单文件大小', help_text="M")

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Transaction(models.Model):
    """ 交易记录 """
    status_choice = (
        (1, '未支付'),
        (2, '已支付')
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choice)

    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引

    user = models.ForeignKey(verbose_name='用户', to='UserInfo', on_delete=models.CASCADE)
    price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy', on_delete=models.CASCADE)

    count = models.IntegerField(verbose_name='数量（年）', help_text='0表示无限期')

    price = models.IntegerField(verbose_name='实际支付价格')

    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Project(models.Model):
    """ 项目表 """
    COLOR_CHOICES = (
        (1, "#56b8eb"),  # 56b8eb
        (2, "#f28033"),  # f28033
        (3, "#ebc656"),  # ebc656
        (4, "#a2d148"),  # a2d148
        (5, "#20BFA4"),  # #20BFA4
        (6, "#7461c2"),  # 7461c2,
        (7, "#20bfa3"),  # 20bfa3,
    )

    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)

    use_space = models.BigIntegerField(verbose_name='项目已使用空间', default=0, help_text='字节')

    star = models.BooleanField(verbose_name='星标', default=False)

    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', on_delete=models.CASCADE)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    bucket = models.CharField(verbose_name='cos桶', max_length=128)
    region = models.CharField(verbose_name='cos区域', max_length=32)

    # 查询：可以省事；
    # 增加、删除、修改：无法完成
    # project_user = models.ManyToManyField(to='UserInfo',through="ProjectUser",through_fields=('project','user'))


class ProjectUser(models.Model):
    """ 项目参与者 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='参与者', to='UserInfo', on_delete=models.CASCADE)
    star = models.BooleanField(verbose_name='星标', default=False)

    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)


class Wiki(models.Model):
    """wiki知识库"""
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="标题", max_length=64)
    content = models.TextField(verbose_name="内容")

    # 自关联
    parent = models.ForeignKey(verbose_name="父文章", to="self", blank=True, null=True, related_name="children",
                               on_delete=models.CASCADE)

    depth = models.IntegerField(verbose_name="深度", default=1)

    def __str__(self):
        return self.title


class FileRepositoy(models.Model):
    project = models.ForeignKey(verbose_name="项目", to="Project", on_delete=models.CASCADE)
    file_type_choices = (
        (1, '文件'),
        (2, '文件夹')
    )
    file_type = models.SmallIntegerField(verbose_name="类型", choices=file_type_choices)
    name = models.CharField(verbose_name="文件名", max_length=255, help_text="文件/文件夹名")
    key = models.CharField(verbose_name="文件存储在cos中的key", max_length=255, null=True, blank=True)
    # int类型最大表示的数据
    file_size = models.BigIntegerField(verbose_name='文件大小', null=True, blank=True, help_text='字节')
    file_path = models.CharField(verbose_name='文件路径', max_length=255, null=True,
                                 blank=True)  # https://桶.cos.ap-chengdu/....
    parent = models.ForeignKey(verbose_name="父级目录", to='self', null=True, blank=True, related_name='child',
                               on_delete=models.CASCADE)

    update_user = models.ForeignKey(verbose_name="最近更新者", to='UserInfo', on_delete=models.CASCADE)
    update_datetime = models.DateTimeField(verbose_name='更新时间', auto_now=True)


class Issues(models.Model):
    """问题"""
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    issues_type = models.ForeignKey(verbose_name='问题类型', to="IssuesType", on_delete=models.CASCADE)
    module = models.ForeignKey(verbose_name='模块', to="Module", null=True, blank=True, on_delete=models.CASCADE)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')

    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True,
                               on_delete=models.CASCADE)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems',
                                on_delete=models.CASCADE)

    create_datetime = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """
    PROJECT_INIT_LIST = ["任务", '功能', 'Bug']

    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='类型名称', max_length=32)

    def __str__(self):
        return self.title


class Module(models.Model):
    """ 模块（里程碑）"""
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='模块名字', max_length=32)


class IssuesReply(models.Model):
    """问题回复"""
    reply_type_choices = (
        (1, '修改记录'),
        (2, '回复'),
    )
    reply_type = models.IntegerField(verbose_name="类型", choices=reply_type_choices)
    issues = models.ForeignKey(verbose_name="问题", to='Issues', on_delete=models.CASCADE)

    content = models.TextField(verbose_name="描述")
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', on_delete=models.CASCADE,
                                related_name='create_reply')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True, on_delete=models.CASCADE)


class ProjectInvite(models.Model):
    """项目邀请码"""
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    code = models.CharField(verbose_name='邀请码', max_length=64, unique=True)
    count = models.PositiveIntegerField(verbose_name='限制数量', null=True, blank=True, help_text='控表示无数量限制')
    use_count = models.PositiveIntegerField(verbose_name='已邀请的数量', default=0)
    period_choices = (
        (30, '30分钟'),
        (60, '60分钟'),
        (300, '5小时'),
        (1440, '24小时'),
    )
    period = models.IntegerField(verbose_name='有效期', choices=period_choices, default=1440)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    creator = models.ForeignKey(verbose_name='创建者', to="UserInfo", related_name='create_invite',
                                on_delete=models.CASCADE)

web/forms/wiki.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

@File  : wiki.py
@Author: WangXiang
@Email : wxlinux@162.com
@Date  : 2020/6/28 15:47
@Tool  : PyCharm
@Desc  : 
'''

from django import forms
from django.forms import ModelForm
from web import models

from web.forms.bootstrap import BootStarpForm

class WikiModeForm(BootStarpForm,ModelForm):
    bootstarp_class_exclude = ['project','depth']

    class Meta:
        model = models.Wiki
        fields = ['id','title','content','parent']



    def __init__(self,request,*args,**kwargs):
        super(WikiModeForm, self).__init__(*args,**kwargs)
        total_data_list = [("","请选择")]
        data_list = models.Wiki.objects.filter(project=request.tracer.project).values_list('id','title')
        total_data_list.extend(data_list)
        self.fields['parent'].choices = total_data_list

web/views/dashboard.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @File  : dashboard.py
# @Author: WangXiang
# @Email : wxlinux@162.com
# @Date  : 2020/7/4 17:04
# @Tool  : PyCharm
# @Desc  :
import collections
import datetime
import time

from django.db.models import Count
from django.shortcuts import render
from django.http import JsonResponse

from web import models


def dashboard(request, project_id):
    # 问题显示面板  .values分组 annotate查询集
    issues_data = models.Issues.objects.filter(project_id=project_id).values('status').annotate(ct=Count('id'))
    # <QuerySet [{'status': 1, 'ct': 3}, {'status': 5, 'ct': 1}]>

    # 有序字典
    status_dict = collections.OrderedDict()
    for key, text in models.Issues.status_choices:
        status_dict[key] = {"text": text, 'count': 0}

    for item in issues_data:
        key = item["status"]
        count = item["ct"]
        status_dict[key]['count'] = count

    # 项目参与者
    user_list = models.ProjectUser.objects.filter(project_id=project_id).values('user_id', 'user__username')

    # 动态
    top_ten_object = models.Issues.objects.filter(project_id=project_id).order_by('-id')[0:10]

    context = {
        'status_dict': status_dict,
        'user_list': user_list,
        'top_ten_object': top_ten_object,
    }

    return render(request, 'dashboard.html', context)


def issues_chart(request, project_id):
    '''在橄榄页面生产图表所需数据'''

    today = datetime.datetime.now().date()
    # datetime.datetime.now() 2020-07-06 15:38:47.483793
    # datetime.datetime.now().date()  2020-07-06

    # 生成30天数据
    date_dict = collections.OrderedDict()
    for i in range(30):
        date = today - datetime.timedelta(days=i)
        date_dict[date.strftime("%Y-%m-%d")] = [time.mktime(date.timetuple()) * 1000, 0]

    result = models.Issues.objects.filter(project_id=project_id,
                                          create_datetime__gte=today - datetime.timedelta(days=30)).extra(
        select={'ctime': "strftime('%%Y-%%m-%%d',web_issues.create_datetime)"}).values('ctime').annotate(ct=Count('id'))
    # <QuerySet [{'ctime': '2020-07-02', 'ct': 5}, {'ctime': '2020-07-03', 'ct': 1}]>
    for item in result:
        date_dict[item['ctime']][1] = item['ct']

    return JsonResponse({'status': True, 'data': list(date_dict.values())})

web/views/setting.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''

@File  : setting.py
@Author: WangXiang
@Email : wxlinux@162.com
@Date  : 2020/7/1 15:15
@Tool  : PyCharm
@Desc  : 
'''
from django.shortcuts import render, redirect
from web import models
from utils.tencent.cos import delete_bucket


def setting(request,project_id):
    return render(request,'setting.html')

def delete(request,project_id):
    #删除项目

    if request.method == "GET":
        return render(request, 'setting_delete.html')

    project_name = request.POST.get('project_name',"")
    if not project_name or project_name != request.tracer.project.name:
        return render(request, 'setting_delete.html',{'error':"项目名称错误"})
     # 项目名写对了则删除（只有创建者可以删除）
    if request.tracer.user != request.tracer.project.creator:
        return render(request, 'setting_delete.html', {'error': "只有项目创建者可删除项目"})

    # 1. 删除桶
    #       - 删除桶中的所有文件（找到桶中的所有文件 + 删除文件 )
    #       - 删除桶中的所有碎片（找到桶中的所有碎片 + 删除碎片 )
    #       - 删除桶
    # 2. 删除项目
    #       - 项目删除
    delete_bucket(request.tracer.project.bucket, request.tracer.project.region)
    models.Project.objects.filter(id=request.tracer.project.id).delete()

    return redirect('project_list')

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 首页 {% endblock %}
{% block css %}
    <style>
        img {
            width: 100%;
        }
    </style>
    
{% endblock %}
{% block content %}
    <div>
        <img src="{% static 'img/index/index-1.png' %}">
        <img src="{% static 'img/index/index-2.png' %}">
        <img src="{% static 'img/index/index-3.png' %}">
        <img src="{% static 'img/index/index-4.png' %}">
    </div>

{% endblock %}


{% block js %}
{% endblock %}

web/templates/invite_join.html
{% extends 'layout/manage.html' %}

{% block title %}加入项目{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div>
        {% if error %}
            <div class="alert alert-danger no-radius">
                <h4><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ error }}</h4>
            </div>
        {% else %}
            <div class="alert alert-success no-radius">
                <h4><i class="fa fa-check-circle" aria-hidden="true"></i> 加入成功 </h4>
                <a href="{% url 'dashboard' project_id=project.id %}">点击跳转至项目</a>
            </div>
        {% endif %}

    </div>

{% endblock %}

web/templates/login.html
{% extends 'layout/basic.html' %}

{% block title %} 用户登录 {% endblock %}
{% block css %}
    <style>
        .error-msg {
            color: red;
        }
    </style>

{% endblock %}
{% block content %}
    <div class="container">
        <div class="account">
            <div class="title">用户登录</div>
            <form method="POST" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name == 'code' %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="row">
                                <div class="col-xs-7">
                                    {{ field }}
                                    <span class="error-msg">{{ field.errors.0 }}</span>
                                </div>
                                <div class="col-xs-5">
                                    <img src="{% url 'image_code' %}" id="imageCode" title="点击更换验证码">
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>
                    {% endif %}
                {% endfor %}

                <div style="float: right;">
                    <a href="{% url 'login_sms' %}">短信验证码登录？</a>
                </div>

                <div class="row">
                    <div class="col-xs-3">
                        <input type="submit" class="btn btn-primary" value="登  录"/>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        //框架完成后自动执行函数
        $(function () {
            //点击更换验证码
            $('#imageCode').click(function () {
                var oldSrc = $(this).attr('src');
                $(this).attr('src',oldSrc + "?"); //index/?name=123
            })
        });

    </script>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}

{% block title %} 短信登录 {% endblock %}
{% block css %}
    <style>
        .error-msg {
            color: red;
        }
    </style>

{% endblock %}
{% block content %}
    <div class="container">
        <div class="account">
            <div class="title">用户短信登录</div>
            <form id="regForm" method="POST" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name == 'code' %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="row">
                                <div class="col-xs-7">
                                    {{ field }}
                                    <span class="error-msg"></span>
                                </div>
                                <div class="col-xs-5">
                                    <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            <span class="error-msg"></span>
                        </div>
                    {% endif %}
                {% endfor %}

                <div style="float: right;">
                    <a href="{% url 'login' %}">用户密码登录？</a>
                </div>

                <div class="row">
                    <div class="col-xs-3">
                        <input id="btnSubmit" type="button" class="btn btn-primary" value="登  录"/>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}


{% block js %}
    <script>
        //框架完成后自动执行函数
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        });

        {#//点击注册#}
        {#function bindClickSubmit() {#}
        {#    $('#btnSubmit').click(function () {#}
        {#        $('.error-msg').empty();#}
        {#        //ajax#}
        {#        $.ajax({#}
        {#            url: '{% url 'register' %}',#}
        {#            type: 'POST',#}
        {#            data: $('#regForm').serialize(),#}
        {#            success: function (data) {#}
        {#                if (data.status) {#}
        {#                    location.href = data.data;#}
        {#                } else {#}
        {#                    $.each(data.error, function (key, value) {#}
        {#                        $('#id_' + key).next().text(value[0])#}
        {#                    })#}
        {#                }#}
        {#            }#}
        {#        })#}
        {#    })#}
        {#}#}

        //点击获取验证码
        function bindClickBtnSms() {
            $('#btnSms').click(function () {
                $('.error-msg').empty();
                //获取用户手机号
                var mobilePhone = $('#id_mobile_phone').val();
                //发送ajax
                $.ajax({
                    url: "{% url 'send_sms' %}",
                    type: "POST",
                    data: {
                        mobile_phone: mobilePhone,
                        tpl: "login",
                        csrfmiddlewaretoken: $(':input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function (data) {
                        //res 后端返回的数据
                        if (data.status) {
                            console.log(data);
                            sendSmsRemind();
                        } else {                           //错误信息
                            // console.log(res); // {status:False, error:{ mobile_phone: ["错误信息"，],code: ["错误信息"，] }  }
                            $.each(data.error, function (key, value) {
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        倒计时
         */
        function sendSmsRemind() {
            var $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true); // 禁用
            var time = 60;
            var remind = setInterval(function () {
                $smsBtn.val(time + '秒重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000)

        }
    </script>
{% endblock %}

web/templates/payment.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 订单 {% endblock %}
{% block css %}

{% endblock %}
{% block content %}
    <div class="container">
        <h2>订单信息（30分钟失效）</h2>
        <table class="table">
            <thead>
            <tr>
                <th>订单</th>
                <th>单价</th>
                <th>数量</th>
                <th>原价</th>
                <th>原订单抵扣</th>
                <th>实际支付</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ policy_object.title }}</td>
                <td>¥{{ policy_object.price }}</td>
                <td>{{ number }}</td>
                <td>¥{{ origin_price }}</td>
                <td>¥{{ balance }}</td>
                <td>¥{{ total_price }}</td>
            </tr>
            </tbody>
        </table>
        {% if transaction %}
            <div class="alert alert-warning">
                <div>原订单抵扣：¥{{ balance }}</div>
                <div style="margin-top: 10px">
                    原订单的时间为 {{ transaction.start_datetime }}
                    ~ {{ transaction.end_datetime }}，且实际支付¥{{ transaction.price }}
                </div>
            </div>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'pay' %}">立即支付</a>
    </div>


{% endblock %}


{% block js %}
{% endblock %}

web/templates/price.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} 套餐 {% endblock %}
{% block css %}
    <style>
        .slogan {
            font-size: 36px;
            text-align: center;
            margin: 50px 0;
        }

    </style>

{% endblock %}
{% block content %}
    <div class="container">
        <div class="slogan">多种方案，使用多种场景</div>
        <div class="row">
            {% for item in policy_list %}
                <div class="col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="text-align: center;">{{ item.title }}</div>
                        <div class="panel-body">

                            <p style="text-align: center;font-size: 25px;">
                                ¥ {{ item.price }} / 年
                            </p>

                        </div>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <form class="form-inline" method="get" action="{% url 'payment' price_id=item.id %}">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-addon">数量</div>
                                            <input type="number" name="number" value="1" class="form-control"
                                                   placeholder="购买数量">
                                            <div class="input-group-btn">
                                                <input type="submit" value="立即购买" class="btn btn-primary">
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </li>
                            <li class="list-group-item">最大项目数量：{{ item.project_num }}</li>
                            <li class="list-group-item">最大项目空间：{{ item.project_space }}G</li>
                            <li class="list-group-item">最大文件支持：{{ item.per_file_size }}M</li>
                            <li class="list-group-item">项目成员：{{ item.project_member }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}


{% block js %}
{% endblock %}